### ISSUE TITLE
fix travis deploy step (tar and upload file to github release)

### ISSUE THREAD

**Issue by joeycozza** [fs-webdev/create-react-app#5]
Currently getting an authentication error with the dpl gem when trying to interact with github.
```
dpl_0
1.60s$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Successfully installed dpl-1.10.4
1 gem installed
dpl.1
Installing deploy dependencies
Successfully installed multipart-post-2.0.0
Successfully installed faraday-0.15.3
Successfully installed public_suffix-3.0.3
Successfully installed addressable-2.5.2
Successfully installed sawyer-0.8.1
Successfully installed octokit-4.6.2
Successfully installed mime-types-2.99.3
Successfully installed dpl-releases-1.10.4
8 gems installed
/home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Bad credentials // See: https://developer.github.com/v3 (Octokit::Unauthorized)
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.3/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.3/lib/faraday/response.rb:61:in `on_complete'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.3/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.3/lib/faraday/rack_builder.rb:143:in `build_response'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.3/lib/faraday/connection.rb:387:in `run_request'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.3/lib/faraday/connection.rb:138:in `get'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/connection.rb:154:in `request'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/connection.rb:19:in `get'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/octokit-4.6.2/lib/octokit/client/users.rb:34:in `user'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-releases-1.10.4/lib/dpl/provider/releases.rb:54:in `user'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-releases-1.10.4/lib/dpl/provider/releases.rb:79:in `setup_auth'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-releases-1.10.4/lib/dpl/provider/releases.rb:83:in `check_auth'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.4/lib/dpl/provider.rb:183:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.4/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.4/lib/dpl/provider.rb:182:in `deploy'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.4/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.4/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/dpl-1.10.4/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/dpl:23:in `<main>'
dpl.2
Preparing deploy
failed to deploy
```

**Comment by joeycozza** [comment]
was able to fix this by using a generated auth token from fs-write.
